### ISSUE TITLE
I think Test App doesn't work

### ISSUE THREAD

**Issue by lwinged** [neurospeech/xamarin-shortcut-badger#1]
[ShortcutBadger] Unable to execute badge
[ShortcutBadger] me.leolin.shortcutbadger.ShortcutBadgeException: Unable to execute badge
[ShortcutBadger]    at me.leolin.shortcutbadger.ShortcutBadger.applyCountOrThrow(ShortcutBadger.java:77)
[ShortcutBadger]    at me.leolin.shortcutbadger.ShortcutBadger.applyCount(ShortcutBadger.java:52)
[ShortcutBadger]    at mono.android.view.View_OnClickListenerImplementor.n_onClick(Native Method)
[ShortcutBadger]    at mono.android.view.View_OnClickListenerImplementor.onClick(View_OnClickListenerImplementor.java:30)
[ShortcutBadger]    at android.view.View.performClick(View.java:5198)
[ShortcutBadger]    at android.view.View$PerformClick.run(View.java:21147)
[ShortcutBadger]    at android.os.Handler.handleCallback(Handler.java:739)
[ShortcutBadger]    at android.os.Handler.dispatchMessage(Handler.java:95)
[ShortcutBadger]    at android.os.Looper.loop(Looper.java:148)
[ShortcutBadger]    at android.app.ActivityThread.main(ActivityThread.java:5417)
[ShortcutBadger]    at java.lang.reflect.Method.invoke(Native Method)
[ShortcutBadger]    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
[ShortcutBadger]    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
[ShortcutBadger] Caused by: me.leolin.shortcutbadger.ShortcutBadgeException: unable to resolve intent: Intent { act=android.intent.action.BADGE_COUNT_UPDATE (has extras) }
[ShortcutBadger]    at me.leolin.shortcutbadger.impl.DefaultBadger.executeBadge(DefaultBadger.java:33)
[ShortcutBadger]    at me.leolin.shortcutbadger.ShortcutBadger.applyCountOrThrow(ShortcutBadger.java:75)
[ShortcutBadger]    ... 12 more

**Comment by neurospeech** [comment]
What is phone model? This library simply embeds https://github.com/leolin310148/ShortcutBadger java library. This may not work in the emulator.

**Comment by lwinged** [comment]
I use a real device LG Nexus 5X (Android 6.0 API 23)

**Comment by ackava** [comment]
Try latest build and let us know if it still does not work.
