### ISSUE TITLE
No badge on Samsung S4 (GT-19295), Android 5.0.1

### ISSUE THREAD

**Issue by espritm** [neurospeech/xamarin-shortcut-badger#3]
Hi NeuroSpeech,

First, thanks a lot for your package nuget !! I use it and it works well on many device, like Samsung A5 2017 (Android 6.0.1)

Unfortunately, I can't get Badges with the following device : Samsung S4 (GT-19295), Android 5.0.1. I get this error in output : 

```
Unable to execute badge
me.leolin.shortcutbadger.ShortcutBadgeException: Unable to execute badge
 	at me.leolin.shortcutbadger.ShortcutBadger.applyCountOrThrow(ShortcutBadger.java:77)
 	at me.leolin.shortcutbadger.ShortcutBadger.applyCount(ShortcutBadger.java:52)
 	at mono.android.view.View_OnClickListenerImplementor.n_onClick(Native Method)
 	at mono.android.view.View_OnClickListenerImplementor.onClick(View_OnClickListenerImplementor.java:30)
 	at android.view.View.performClick(View.java:5197)
 	at android.view.View$PerformClick.run(View.java:20926)
 	at android.os.Handler.handleCallback(Handler.java:739)
 	at android.os.Handler.dispatchMessage(Handler.java:95)
 	at android.os.Looper.loop(Looper.java:145)
 	at android.app.ActivityThread.main(ActivityThread.java:5942)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:372)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
 Caused by: me.leolin.shortcutbadger.ShortcutBadgeException: unable to resolve intent: Intent { act=android.intent.action.BADGE_COUNT_UPDATE (has extras) }
 	at me.leolin.shortcutbadger.impl.DefaultBadger.executeBadge(DefaultBadger.java:33)
 	at me.leolin.shortcutbadger.ShortcutBadger.applyCountOrThrow(ShortcutBadger.java:75)
 	... 13 more
```

Do you have any idea of why it doesn't work ? I used your app sample to test.

Thanks in advance

**Comment by Nininea-zz** [comment]
I have the same problem. any solution?

**Comment by neurospeech** [comment]
We have released new version, please confirm if it works.

**Comment by espritm** [comment]
Thank you so much !!
Yes I confirm, it works fine with version 1.1.982 :)

**Comment by Nininea-zz** [comment]
It is fixed
